dificultad: 1
dificultad_message: 'Term %term already exists in vocabulary %vocabulary.'
origen: 1
origen_message: 'Term %term already exists in vocabulary %vocabulary.'
ingredientes: 1
ingredientes_message: 'Term %term already exists in vocabulary %vocabulary.'
